name: matrix_mqtt_control
description: A simple Flutter app to control LED Matrix via MQTT
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
